services:
  db:
    image: postgres:17
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234}
      - POSTGRES_DB=${DB_NAME:-db}
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8080:80
    volumes:
        - pgadmin-data:/var/lib/pgadmin
        - pgadmin-config:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
  pgadmin-config:
